export {
  default,
  Animations,
  breakpoints,
  colours,
  editionBreakpoints,
  editionBreakpointWidths,
  editionMaxWidth,
  sliceContentMaxWidth,
  fonts,
  fontFactory,
  fontSizes,
  getEditionBreakpoint,
  lineHeight,
  scales,
  spacing,
  globalSpacingStyles,
  tabletRowPadding,
  tabletWidth,
  tabletWidthMax,
  themeFactory
} from './src/styleguide';
