export {
  IconFacebook,
  IconForwardArrow,
  IconStar,
  IconCopyLink,
  IconSaveBookmark,
  IconTwitter,
  IconVideo,
  IconVideo360Player,
  TheSTLogo,
  TheTimesLogo,
  CloseIcon,
  DeleteIcon,
  GlassMagnifierIcon,
  ImageIcons,
} from "./src/icons";
